openapi: 3.0.0
info:
    title: Base User API
    version: '1.0'
    contact:
        name: Nikolaus Trixner
        url: 'https://nikolaus.trixner.eu'
        email: nikolaus@trixner.eu
    license:
        name: MIT
        url: 'https://opensource.org/licenses/MIT'
    description: Basic User API for other APIs
servers:
- url: 'http://localhost:8080'
paths:
    '/user/{userId}':
        get:
            summary: Get a specific user
            responses:
                '200':
                    description: OK
                    headers: {}
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UserDto'
                            examples: {}
                '401':
                    description: User not logged in
                '403':
                    description: User not authorized to access User data
                '404':
                    description: User not found
            security:
            - auth: []
            parameters: []
            requestBody:
                content:
                    application/json:
                        schema:
                            type: string
                description: ''
            description: Returns a specific user
            operationId: getUserById
        parameters:
        - schema:
              type: string
          name: userId
          in: path
          description: 'The user ID of the user, or null for the currently logged in user'
          required: true
    /user/userlist:
        get:
            summary: Your GET endpoint
            responses:
                '200':
                    description: OK
                    headers: {}
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    pageSize:
                                        type: number
                                    pagePos:
                                        type: number
                                    ordering:
                                        type: string
                                    items:
                                        type: array
                                        items:
                                            $ref: '#/components/schemas/UserDto'
                '401':
                    description: User not logged in
                '403':
                    description: User not authorized to access User data
            description: 'Return a paginated list of all users. If the provided pagination is not correct, the first 20 users will be returned instead.'
            parameters:
            - schema:
                  type: integer
              in: query
              name: pageSize
              description: 'The Size of the requested pages, or null for infinite page size'
            - schema:
                  type: integer
              in: query
              name: pagePos
              description: 'The number of Page that should currently be shown, or null for first page'
            - schema:
                  type: string
              in: query
              name: ordering
              description: 'ASC for ascending, DESC for descending, or null to not order the list'
            operationId: listUsers
            security:
            - auth: []
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties: {}
        parameters: []
    /user/login:
        post:
            summary: ''
            responses:
                '202':
                    description: Accepted
                '401':
                    description: Unauthorized
            operationId: loginUser
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LoginDto'
            description: Logs a user in with username and password
        parameters: []
    /user/registration/register:
        post:
            summary: ''
            responses:
                '201':
                    description: Created
                '401':
                    description: Unauthorized
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RegistrationDto'
            description: 'Registers a new user by putting in username, email and password'
            operationId: registerUser
        parameters: []
    /user/logout:
        post:
            summary: ''
            responses:
                '200':
                    description: OK
                '400':
                    description: Bad Request
            operationId: logoutUser
            description: Logs the current user out and destroys the current session
            security:
            - auth: []
        parameters: []
    '/user/registration/confirmRegistration/{registrationQuery}':
        post:
            summary: ''
            responses:
                '200':
                    description: OK
                '400':
                    description: Bad Request
            operationId: confirmRegistration
            description: Confirms the registration of a new user by activating via a link that was sent via email.
        parameters:
        - schema:
              type: string
          name: registrationQuery
          in: path
          required: true
          description: "The registration query parameter that was sent via mail to the new user's address"
    /user/userlist/num:
        get:
            summary: Your GET endpoint
            tags: []
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    count:
                                        type: integer
                '401':
                    description: Unauthorized
            operationId: getUserCount
            description: Returns the amount of users that currently exist.
            security:
            - auth: []
        parameters: []
    /user:
        get:
            summary: Your GET endpoint
            tags: []
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UserDto'
                '401':
                    description: Unauthorized
            description: Returns the current user
            operationId: getCurrentUser
            security:
            - auth: []
    /user/forgotPassword:
        get:
            summary: Your GET endpoint
            responses:
                '200':
                    description: Mail was sent
                '404':
                    description: User/Mail combination not found
            description: Call if the user forgot their password and want to get sent a mail with a password change link
            operationId: forgotPassword
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ForgotPasswordDto'
    /user/forgotPassword/resetPassword:
        get:
            summary: Your GET endpoint
            tags: []
            responses:
                '200':
                    description: OK
                '400':
                    description: Bad Request
                '404':
                    description: Not Found
            description: Resets a password based on a password reset request
            operationId: resetPasswordRequest
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/PasswordResetDto'
        parameters: []
components:
    schemas:
        UserDto:
            title: UserDto
            type: object
            properties:
                id:
                    type: string
                    format: uuid
                username:
                    type: string
                email:
                    type: string
                    format: email
        RegistrationDto:
            title: RegistrationDto
            type: object
            properties:
                username:
                    type: string
                email:
                    type: string
                    format: email
                password:
                    type: string
                    format: password
            required:
            - username
            - email
            - password
        LoginDto:
            title: LoginDto
            type: object
            properties:
                username:
                    type: string
                password:
                    type: string
                    format: password
            required:
            - username
            - password
        ForgotPasswordDto:
            title: ForgotPasswordDto
            type: object
            properties:
                username:
                    type: string
                email:
                    type: string
                    format: email
            required:
            - username
            - email
        PasswordResetDto:
            title: PasswordResetDto
            type: object
            properties:
                newPassword:
                    type: string
                requestId:
                    type: string
                    format: uuid
            required:
            - newPassword
            - requestId
    securitySchemes:
        auth:
            type: http
            scheme: Bearer
            description: SESSIONID
