/**
 * BaseAPI
 * Base test at.ntrixner.base.api for future projects
 *
 * OpenAPI spec version: 1.0
 * Contact: nikolaus@trixner.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MessageDTO { 
    message?: string;
}
