<!DOCTYPE html>
<html>
<body style="text-align: center;">
<h1>Willkommen ${username}!
</h1>
<p>Du hast dich bei ${applicationName} registriert. Bitte folge diesem Link, um die Anmeldung abzuschließen:</p>
<p><a href="${url}/${token}">Klick mich!</a></p>
<p>Falls dieser Link nicht funktioniert, kopiere folgenden Text in die Suchleiste deines Internet-Browsers:</p>
<p>${url}/${token}</p>
<p>Falls du dich nicht bei ${applicationName} registrieren wolltest, kannst du diese Mail ignorieren oder einen
    Administrator kontaktieren.</p>
</body>
</html>