application:
  name: BASE APPLICATION

email:
  sender: yourmail@gmx.at
  host: mail.gmx.com
  password: yourpass
  port: 587
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
  username: yourUser

logging:
  level:
    eu:
      trixner:
        base:
          server: INFO
    org:
      hibernate: ERROR
      springframework:
        security: DEBUG
        web: INFO

spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:testdb
    username: databaseuser
  freemarker:
    cache: false
    suffix: .ftl
    template-loader-path: file:src/main/resources/templates/
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false

user:
  passwordReset:
    requestCleanupRate: 300000
    requestExpiration: 86400000
  registration:
    requestCleanupRate: 300000
    requestExpiration: 86400000

jwt:
  #Signing key for HS512 algorithm
  #You can use the page http://www.allkeysgenerator.com/ to generate all kinds of keys
  secret: n2r5u8x/A%D*G-KaPdSgVkYp3s6v9y$B&E(H+MbQeThWmZq4t7w!z%C*F-J@NcRf
  token:
    expiration: 900000
    #The period of milliseconds until expiration, where we refresh the token on any successful call
    #If 0, tokens don't get refreshed
    #If larger than expiration, tokens never expire
    refresh: 840000
    removeStaleTokenRate: 60000
