openapi: 3.0.0
info:
  title: Base User API
  version: '1.0'
  contact:
    name: Nikolaus Trixner
    url: 'https://nikolaus.trixner.eu'
    email: nikolaus@trixner.eu
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  description: Basic User API for other APIs
tags:
  - name: User
    description: Methods used for registering, forgetting passwords, login and logout
  - name: Userlist
    description: Methods used for the Userlist
servers:
  - url: 'http://{host}:{port}/api'
    variables:
      host:
        default: 'localhost'
        description: the host address of the application
      port:
        default: '8080'
        description: the port of the application
security:
  - auth: [ ]
paths:
  /auth/login:
    $ref: './methods/auth/login.yaml'

  /auth/logout:
    $ref: './methods/auth/logout.yaml'

  /auth/userTypes:
    $ref: './methods/auth/userTypes.yaml'

  '/user/{userId}':
    $ref: './methods/user/byId.yaml'

  /user/registration/register:
    $ref: './methods/user/register.yaml'

  '/user/registration/confirmRegistration/{uuid}':
    $ref: './methods/user/registerConfirm.yaml'

  /user:
    $ref: './methods/user/current.yaml'

  /user/available/username/{username}:
    $ref: './methods/user/nameAvailable.yaml'

  /user/available/email/{email}:
    $ref: './methods/user/mailAvailable.yaml'

  /user/change/save:
    $ref: './methods/user/change.yaml'

  /user/create:
    $ref: './methods/user/create.yaml'

  /user/delete/{uuid}:
    $ref: './methods/user/delete.yaml'

  /user/change/changePassword:
    $ref: './methods/user/passwordChange.yaml'

  /user/forgotPassword:
    $ref: './methods/user/passwordForgot.yaml'

  /user/forgotPassword/resetPassword:
    $ref: './methods/user/passwordReset.yaml'

  /userlist:
    $ref: './methods/userlist/userlist.yaml'

  /userlist/num:
    $ref: './methods/userlist/amount.yaml'

components:
  securitySchemes:
    auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
