GET http://localhost:8080/userlist
Content-Type: application/json

{
  "page": 0,
  "pageSize": 2,
  "orderField": "id",
  "orderDirection": "ASC"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json


###

GET http://localhost:8080/user
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJzZWN1cmUtYXBpIiwiYXVkIjoic2VjdXJlLWFwcCIsInN1YiI6InVzZXIiLCJleHAiOjE1ODA0MTMyODksInJvbCI6WyJVU0VSIl19.wSBGrfR4xpf97EXic_au03cvh-Y5YkZalzqbazI8j3yccibXL-D5BDH0IXixbPpUcKAG0Jtaqv1Eg4OwmOkvaA

###

GET http://localhost:8080/userlist
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJzZWN1cmUtYXBpIiwiYXVkIjoic2VjdXJlLWFwcCIsInN1YiI6InVzZXIiLCJleHAiOjE1ODA0MTMwMjksInJvbCI6WyJVU0VSIl19.fntgPYgClBlu_6Z54PDrWY6VuyKlN3ArUeg9nX9HHpJd9X4jWazTIrs-0qR3Qr6jf4pFv--ERqg_-sX-03w05A
Content-Type: application/json

{
  "page": 0,
  "pageSize": 2,
  "orderField": "id",
  "orderDirection": "ASC"
}

###

POST http://localhost:8080/user/changePassword
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJzZWN1cmUtYXBpIiwiYXVkIjoic2VjdXJlLWFwcCIsInN1YiI6InVzZXIiLCJleHAiOjE1ODA0MTI0MDAsInJvbCI6WyJVU0VSIl19.IxHQmsY7njCEZeMPQqVSAG97bnFyJpEYmeDyKSkUb6bgp8ZqmDgXEUHSDAGUndlEIClQMyLZp3KgNNnbw79yCA
Content-Type: application/json

{
  "oldPassword": "abc",
  "newPassword": "user"
}

###

POST http://localhost:8080/auth/logout
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJzZWN1cmUtYXBpIiwiYXVkIjoic2VjdXJlLWFwcCIsInN1YiI6InVzZXIiLCJleHAiOjE1ODA0MTMwMjksInJvbCI6WyJVU0VSIl19.fntgPYgClBlu_6Z54PDrWY6VuyKlN3ArUeg9nX9HHpJd9X4jWazTIrs-0qR3Qr6jf4pFv--ERqg_-sX-03w05A

###

GET http://localhost:8080/userlist
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJzZWN1cmUtYXBpIiwiYXVkIjoic2VjdXJlLWFwcCIsInN1YiI6InVzZXIiLCJleHAiOjE1ODA0MTE2NTcsInJvbCI6WyJVU0VSIl19.m8kfcQ0ig90wgPDrGafFjoWQGiAsQuP2qxgLWhG-HEcvrR4ES02AGEcXlFOz5AnjDfHz4m8s7iXHcCLuJTNeBw
Content-Type: application/json

{
  "page": 0,
  "pageSize": 2,
  "orderField": "id",
  "orderDirection": "ASC"
}

###

GET http://localhost:8080/userlist/num
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJzZWN1cmUtYXBpIiwiYXVkIjoic2VjdXJlLWFwcCIsInN1YiI6InVzZXIiLCJleHAiOjE1Nzk4ODMxNDUsInJvbCI6WyJVU0VSIl19.cAlVwBDud42GIvrwrO30xp1vkUc7nYkoIn6yty8iOzFD4c4-Fg5m7C5yaCH_FEkUHadOwbCELCIpxHYlaPbfzg

###

POST http://localhost:8080/user/registration/register
Content-Type: application/json

{
  "username": "Krampus",
  "email": "n.trixner@gmx.at",
  "password": "asdf1234"
}

###
GET http://localhost:8080/user/forgotPassword
Content-Type: application/json

{
  "username": "user",
  "email": "user@test.com"
}

###

GET http://localhost:8080/user/forgotPassword/resetPassword
Content-Type: application/json

{
  "token": "MSxN7pUY",
  "newPassword": "abc"
}

###
