<!DOCTYPE html>
<html>
<body style="text-align: center;">
<h1>Welcome ${username}!
</h1>
<p>You have registered for ${applicationName}. Please follow the below link to reset your password:</p>
<p><a href="${url}/${token}">Click here!</a></p>
<p>If the link doesn't work, try copying the following and pasting it into the address bar of your browser:</p>
<p>${url}/${token}</p>
<p>If you have not registered for ${applicationName} and you think this mail is an error, please ignore it or contact
    the system administrator.</p>
</body>
</html>