export class RightsConstants {
  public static ROLE_USER_CAN_SEE_SELF = 'ROLE_USER_CAN_SEE_SELF';
  public static ROLE_USER_CAN_CHANGE_PASSWORD = 'ROLE_USER_CAN_CHANGE_PASSWORD';
  public static ROLE_USER_CAN_WATCH_USERLIST = 'ROLE_USER_CAN_WATCH_USERLIST';
  public static ROLE_USER_CAN_CREATE_USER = 'ROLE_USER_CAN_CREATE_USER';
  public static ROLE_USER_CAN_GET_USER_BY_ID = 'ROLE_USER_CAN_GET_USER_BY_ID';
  public static ROLE_USER_CAN_PROMOTE_USERS = 'ROLE_USER_CAN_PROMOTE_USERS';
}
